(() => {
  "use strict";
  const KEY="acalma_cupons";
  const defaults=[{code:"ACALMA10",type:"promo",value:10,mode:"percent",minimum:0,expires:"2026-12-31",limit:null,used:0,active:true},{code:"BEMVINDA20",type:"promo",value:20,mode:"fixed",minimum:50,expires:"2026-10-31",limit:50,used:8,active:true}];
  const read=()=>{try{const value=JSON.parse(localStorage.getItem(KEY));return Array.isArray(value)?value:defaults}catch{return defaults}};
  const save=value=>localStorage.setItem(KEY,JSON.stringify(value));
  const money=value=>Number(value||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
  const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  const toast=message=>{const el=document.querySelector("#toast");el.textContent=message;el.classList.add("visivel");setTimeout(()=>el.classList.remove("visivel"),2600)};
  let coupons=read(); save(coupons);
  const tbody=document.querySelector("#tabelaCuponsAdmin"),search=document.querySelector("#buscaCupomAdmin"),status=document.querySelector("#filtroStatusCupom"),modal=document.querySelector("#modalCupom");
  function render(){const term=search.value.trim().toLowerCase(),filter=status.value,list=coupons.filter(c=>c.type!=="troca"&&c.code.toLowerCase().includes(term)&&(filter==="todos"||(filter==="ativo")===Boolean(c.active)));tbody.innerHTML=list.length?list.map(c=>`<tr><td><strong>${esc(c.code)}</strong></td><td>${c.mode==="percent"?"Percentual":"Valor fixo"}</td><td>${c.mode==="percent"?`${Number(c.value)}%`:money(c.value)}</td><td>${money(c.minimum)}</td><td>${c.expires?new Date(c.expires+"T12:00").toLocaleDateString("pt-BR"):"—"}</td><td>${Number(c.used||0)}${c.limit?` de ${c.limit}`:""}</td><td><span class="status-pill ${c.active?"ativo":"inativo"}">${c.active?"ativo":"inativo"}</span></td><td><div class="acoes-tabela"><button type="button" data-edit="${esc(c.code)}">Editar</button><button type="button" data-status="${esc(c.code)}">${c.active?"Inativar":"Ativar"}</button></div></td></tr>`).join(""):'<tr><td colspan="8" class="tabela-vazia">Nenhum cupom encontrado.</td></tr>';document.querySelector("#contagemCupons").textContent=`${list.length} cupom(ns) promocional(is)`}
  function open(coupon=null){document.querySelector("#formCupom").reset();document.querySelector("#tituloModalCupom").textContent=coupon?"Editar cupom":"Novo cupom";document.querySelector("#cupomOriginal").value=coupon?.code||"";document.querySelector("#cupomCodigo").value=coupon?.code||"";document.querySelector("#cupomModo").value=coupon?.mode||"percent";document.querySelector("#cupomValor").value=coupon?.value||"";document.querySelector("#cupomMinimo").value=coupon?.minimum||0;document.querySelector("#cupomValidade").value=coupon?.expires||"";document.querySelector("#cupomLimite").value=coupon?.limit||"";modal.showModal()}
  search.addEventListener("input",render);status.addEventListener("change",render);document.querySelector("#novoCupom").addEventListener("click",()=>open());
  document.querySelectorAll("[data-close-coupon]").forEach(button=>button.addEventListener("click",event=>{event.preventDefault();modal.close()}));
  tbody.addEventListener("click",event=>{const edit=event.target.dataset.edit,toggle=event.target.dataset.status;if(edit)open(coupons.find(c=>c.code===edit));if(toggle){const c=coupons.find(c=>c.code===toggle);c.active=!c.active;save(coupons);render();toast(`Cupom ${c.active?"ativado":"inativado"}.`)}});
  document.querySelector("#formCupom").addEventListener("submit",event=>{event.preventDefault();const original=document.querySelector("#cupomOriginal").value,code=document.querySelector("#cupomCodigo").value.trim().toUpperCase();if(coupons.some(c=>c.code===code&&c.code!==original))return toast("Já existe um cupom com esse código.");const old=coupons.find(c=>c.code===original),data={code,type:"promo",mode:document.querySelector("#cupomModo").value,value:Number(document.querySelector("#cupomValor").value),minimum:Number(document.querySelector("#cupomMinimo").value),expires:document.querySelector("#cupomValidade").value,limit:Number(document.querySelector("#cupomLimite").value)||null,used:old?.used||0,active:old?.active??true};coupons=original?coupons.map(c=>c.code===original?data:c):[...coupons,data];save(coupons);modal.close();render();toast("Cupom salvo com sucesso.")});
  render();
})();
