(() => {
 "use strict";
 const ORDER_KEY="acalma_pedidos",PRODUCT_KEY="acalma_produtos",COUPON_KEY="acalma_cupons",NOTE_KEY="acalma_notificacoes",LOG_KEY="acalma_logs";
 const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
 const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
 const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
 const money=value=>Number(value||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
 const toast=message=>{const el=document.querySelector("#toast");el.textContent=message;el.classList.add("visivel");setTimeout(()=>el.classList.remove("visivel"),2600)};
 const normalize=status=>({"EM TROCA":"TROCA SOLICITADA","TROCA AUTORIZADA":"TROCA ACEITA","TROCADO":"TROCA PROCESSADA"}[status]||status);
 const orders=()=>read(ORDER_KEY,[]).map(order=>order.exchange?{...order,exchange:{...order.exchange,status:normalize(order.exchange.status)}}:order);
 const note=message=>{const list=read(NOTE_KEY,[]);list.unshift({id:Date.now(),message,date:new Date().toISOString(),read:false});write(NOTE_KEY,list)};
 const log=(action,data)=>{const list=read(LOG_KEY,[]);list.unshift({date:new Date().toISOString(),user:"Administrador local",action,data});write(LOG_KEY,list.slice(0,100))};
 const listEl=document.querySelector("#listaTrocas"),search=document.querySelector("#buscaTroca"),filter=document.querySelector("#filtroTroca");
 function exchangeRows(){return orders().filter(order=>order.exchange).map(order=>{const item=order.items[order.exchange.item]||order.items[0]||{};return {order,item,exchange:order.exchange}})}
 function actions(row){const status=row.exchange.status,id=row.order.id;if(status==="TROCA SOLICITADA")return `<span class="troca-verificacao">Confira item e quantidade antes de aprovar</span><button data-action="accept" data-id="${id}" class="troca-btn primario">Aprovar devolução</button><button data-action="deny" data-id="${id}" class="troca-btn negar">Negar</button>`;if(status==="TROCA ACEITA")return `<span class="troca-espera">Aguardando despacho do cliente</span><button data-action="sent" data-id="${id}" class="troca-btn secundario">Registrar item enviado</button>`;if(status==="ITEM ENVIADO")return `<label class="troca-stock"><input type="checkbox" data-stock="${id}" ${row.exchange.returnStock!==false?"checked":""}> Retornar ao estoque</label><button data-action="receive" data-id="${id}" class="troca-btn primario">Confirmar recebimento</button>`;if(status==="ITEM RECEBIDO")return `<button data-action="process" data-id="${id}" class="troca-btn primario">Processar e gerar cupom</button>`;if(status==="TROCA PROCESSADA")return `<span class="troca-coupon">Cupom ${esc(row.exchange.couponCode||"gerado")}</span>`;return '<span class="troca-espera">Solicitação encerrada</span>'}
 function render(){const term=search.value.trim().toLowerCase(),status=filter.value,rows=exchangeRows().filter(row=>(status==="todos"||row.exchange.status===status)&&`${row.order.code} ${row.order.client} ${row.item.nome} ${row.exchange.reason||""}`.toLowerCase().includes(term));const all=exchangeRows();document.querySelector("#trocaResumo").innerHTML=`<span><strong>${all.length}</strong> solicitações</span><span><strong>${all.filter(r=>!["TROCA PROCESSADA","TROCA NEGADA"].includes(r.exchange.status)).length}</strong> em andamento</span>`;listEl.innerHTML=rows.length?rows.map(row=>`<article class="troca-admin-card"><div class="troca-identificacao"><span class="eyebrow">${esc(row.order.code)}</span><h3>${esc(row.item.nome||"Item")}</h3><p>${esc(row.order.client||"Cliente")} · <strong>${row.exchange.quantity||row.item.quantidade||1} unidade(s) solicitada(s)</strong></p><small>${esc(row.exchange.reason||"Motivo não informado")}</small></div><div class="troca-etapa"><span class="status-pill troca-${row.exchange.status.toLowerCase().replaceAll(" ","-")}">${esc(row.exchange.status)}</span><small>Solicitada em ${new Date(row.exchange.requestedAt||row.order.date).toLocaleDateString("pt-BR")}</small></div><div class="troca-admin-actions">${actions(row)}</div></article>`).join(""):'<div class="app-empty admin-card"><h3>Nenhuma troca encontrada</h3><p>Altere os filtros ou aguarde uma solicitação do cliente.</p></div>'}
 function update(id,handler){const list=orders(),order=list.find(item=>item.id===id);if(!order?.exchange)return;handler(order);write(ORDER_KEY,list);render()}
 listEl.addEventListener("change",event=>{if(event.target.dataset.stock)update(Number(event.target.dataset.stock),order=>order.exchange.returnStock=event.target.checked)});
 listEl.addEventListener("click",event=>{const button=event.target.closest("[data-action]");if(!button)return;const id=Number(button.dataset.id),action=button.dataset.action;if(action==="accept")update(id,order=>{order.exchange.status="TROCA ACEITA";note(`Troca do pedido ${order.code} aceita. Informe o envio do item.`);log("Troca aceita",{code:order.code})});if(action==="sent")update(id,order=>{order.exchange.status="ITEM ENVIADO";note(`Envio do item da troca do pedido ${order.code} registrado.`);log("Item de troca enviado",{code:order.code})});if(action==="deny"){const reason=prompt("Informe o motivo da recusa:");if(!reason?.trim())return toast("Informe o motivo para negar a troca.");update(id,order=>{order.exchange.status="TROCA NEGADA";order.exchange.denialReason=reason.trim();note(`Troca do pedido ${order.code} negada: ${reason.trim()}`);log("Troca negada",{code:order.code,reason:reason.trim()})})}if(action==="receive")update(id,order=>{order.exchange.status="ITEM RECEBIDO";note(`Item da troca do pedido ${order.code} recebido pela loja.`);log("Item de troca recebido",{code:order.code})});if(action==="process")update(id,order=>{const item=order.items[order.exchange.item]||order.items[0],quantity=order.exchange.quantity||item.quantidade,code="TR"+String(Date.now()).slice(-6);if(order.exchange.returnStock!==false){const products=read(PRODUCT_KEY,[]),product=products.find(p=>p.nome===item.nome);if(product)product.estoque+=quantity;write(PRODUCT_KEY,products)}const coupons=read(COUPON_KEY,[]);coupons.push({code,type:"troca",value:item.preco*quantity,mode:"fixed",active:true,clientId:order.clientId});write(COUPON_KEY,coupons);order.exchange.status="TROCA PROCESSADA";order.exchange.couponCode=code;note(`Troca do pedido ${order.code} processada. Cupom ${code} disponível.`);log("Troca processada",{code:order.code,coupon:code,quantity});toast("Troca processada e cupom gerado.")})});
 search.addEventListener("input",render);filter.addEventListener("change",render);render();
})();
